[package]
name = "rust-web-app"
version = "0.1.0"
authors = ["pranaysaha <saha.pranay25@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.1.0"